### ISSUE TITLE
Understanding of the routableSubnetwork parameter in the OSM converter

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/pt2matsim#118]
Hello everyone,

I am currently struggling with OSM tram network conversion. Basically, in my modelled city there are roads shared by trams, cars and buses. 

I went through some real links in the OSM. Noticed that the roads with tram lines are actually divided into three parts: two are for `railway=tram` line, and the other is a tertiary line.

@sebhoerl  offered me several useful suggestions regarding my previous question (which you can find here: https://github.com/matsim-org/matsim-code-examples/issues/397#issuecomment-658866756). Actually I have done a lot of related tests, such as defining "railway=tram" link to "tram" MATSim links, adding one routableSubnetwork section which has "allowedTransportModes" = "bus,tram" and "subnetworkMode"=tram.

The results are still not satisfying, either the "tram platform" will have no suitable modes (only pt in the modes allowed), or some links that are not "railway=tram" can allow tram driving on them. Meanwhile, I have seen other modes (e.g. subway), which I didn't make any setting in my OSMConfig file, but there actually are several lines for them.

I guess I just don't get the reason for setting the routableSubnetwork and wayDefaultParams, I went through some deep code but the confusion goes deeper, and I really don't know what should I set now. Can anyone make some further clarification for me? I will be very appreciated for your help!

Thanks in advance :)

**Comment by jingjunL** [comment]
> It is actually an interesting issue. Maybe we'd even need to add some additional code to get it right. Could you maybe create a minimal example of an OSM file that structures a road + tram the way you describe, just for testing purposes?

Hello Sebastian,

Thanks for your quick reply.

I selected a 500m street. As you may see, the "Avenue Adolphe Buyl" looks like this on the street view:
![image](https://user-images.githubusercontent.com/63421908/87941599-ab3f1080-ca9b-11ea-872c-d983a99c2396.png)

And, on the OSM, its structure looks like what I described: two are for railway=tram line, and the other is a tertiary line.
![image](https://user-images.githubusercontent.com/63421908/87941739-df1a3600-ca9b-11ea-939d-29c707ce6b5b.png)

Github doesn't support uploading of OSM file, so I change it into .txt. Don't know if that works
[map.txt](https://github.com/matsim-org/pt2matsim/files/4947891/map.txt)

If there's anything that I can help, please do let me know.

Cheers :)

**Comment by jingjunL** [comment]
> It is actually an interesting issue. Maybe we'd even need to add some additional code to get it right. Could you maybe create a minimal example of an OSM file that structures a road + tram the way you describe, just for testing purposes?

Here's also the link for Google Map. Thanks :)

https://www.google.be/maps/place/Buyl/@50.8174198,4.3802668,18z/data=!4m5!3m4!1s0x47c3c4c2edbabd11:0x5697b1f12c4f336e!8m2!3d50.8174421!4d4.3806719

**Comment by sebhoerl** [comment]
Ok, I see. But in this case basically there is not really any information in the OSM data conveying that the tram line shares the street space, right?

**Comment by sebhoerl** [comment]
I guess the interesting references are:
https://wiki.openstreetmap.org/wiki/Tag:railway%3Dtram
https://wiki.openstreetmap.org/wiki/Trams
https://wiki.openstreetmap.org/wiki/Key:embedded_rails

As far as I see there is nothing wrong with how OSM is converted right now, because your OSM data doesn't really tell otherwise. Reading these pages, I think that correctly the `highway` segment should be tagged with `embedded_rails=tram`. Only then would some converter even know that the tracks are on the street. And once this information is available we could try to match tram tracks with parallel roads, but still it sounds messy :) 

So you could either go this way (tagging it, and then modifying some converter code, either here or in the TU Berlin converter), or you could find those cases in Brussels and adjust them manually.

Another option might be that you create the network as before, but then, once you have the `network.xml.gz` you write some automated script that searches for links with `tram` modes that run closely and parallel to other links with `car` mode and then merge them together ...

Maybe I'm missing something and @polettif has a better idea :)

**Comment by jingjunL** [comment]
> I guess the interesting references are:
> https://wiki.openstreetmap.org/wiki/Tag:railway%3Dtram
> https://wiki.openstreetmap.org/wiki/Trams
> https://wiki.openstreetmap.org/wiki/Key:embedded_rails
> 
> As far as I see there is nothing wrong with how OSM is converted right now, because your OSM data doesn't really tell otherwise. Reading these pages, I think that correctly the `highway` segment should be tagged with `embedded_rails=tram`. Only then would some converter even know that the tracks are on the street. And once this information is available we could try to match tram tracks with parallel roads, but still it sounds messy :)
> 
> So you could either go this way (tagging it, and then modifying some converter code, either here or in the TU Berlin converter), or you could find those cases in Brussels and adjust them manually.
> 
> Another option might be that you create the network as before, but then, once you have the `network.xml.gz` you write some automated script that searches for links with `tram` modes that run closely and parallel to other links with `car` mode and then merge them together ...
> 
> Maybe I'm missing something and @polettif has a better idea :)

I see. That's very detailed. So actually it should be the deficiencies of Brussels OSM data :)

Since the data cannot imply these roads with tram, I will just use the default config for now, so that my trams will be treated as a single system similar to the subway 😓

Can I ask another question about the setting? The `oneway` parameter in the wayDefaultParams of `highway=tertiary` is false, what does this mean? Does that mean all the converted tertiary link will not be oneway? So what the converter will do for the road that is currently oneway? Will it change the them into dual ways?

**Comment by sebhoerl** [comment]
If oneway=false, the converter will create a link in each direction, because all the links in MATSim are uni-directional.

**Comment by jingjunL** [comment]
> If oneway=false, the converter will create a link in each direction, because all the links in MATSim are uni-directional.

Get it! Thank you, Sebastian.

My problem is solved, so I will close this issue now.

Have a nice evening :)

**Comment by polettif** [comment]
> Maybe I'm missing something and @polettif has a better idea :)

I don't :) I always suggest updating the osm source instead of fiddling with any intermediate product (i.e. the MATSim network) because better osm data is useful for many other purposes. Embedded rails are indeed very interesting and could be implemented in the converter. I'll open a issue to keep track of this.
