### ISSUE TITLE
Differences between pt and "bus, subway"

### ISSUE THREAD

**Issue by CianGraham** [matsim-org/pt2matsim#120]
Dear pt2matsim community,

I used pt2matsim as a tool for generating my multimode network. It went smoothly, with 222 artificial links, 52 loop warnings, 73 direction change warnings and 23 travel time warnings. Some questions/confusion raised at present, and I will be grateful if you can help me to solve some of these:

1) My network is from OSM, but still, there are 222 artificial links created, and 95% of them is for the mode "subway". Generally, these artificial links are mostly located at the outskirts of my city area. I guess the reason is: the distance between stations in these areas is longer, so pt2matsim created them because they are more likely to exceed the minimal cost. Have you encountered any similar problems?

2) Are the remaining number of warning (loop, direction and travel time) acceptable for simulation? I know it depends on a specific location, however, how much on average one should expect for these warnings?

3) I can see there are modes "pt" and "bus, subway" in my network.xml. What's the reason for having the mode "pt"? I mean, we already have the mode "bus, subway" in the network, don't we?

Maybe I have too many questions, but thank you very much in advance ;)

**Comment by polettif** [comment]
Does the OSM network have any subway links and do the [transportModeAssignments](https://github.com/matsim-org/pt2matsim/wiki/PTMapper-algorithm-and-config-parameters#creating-mode-dependent-router) match the network links? Because if there are no links to match it's likely there . In general, artificial links for subway routes are not really problematic as they don't interact with other modes. It's more of a visualisation issue.

> Are the remaining number of warning (loop, direction and travel time) acceptable for simulation?

That's generally hard to tell. As you say it depends on the situation (network and number of routes) but these numbers don't seem that high.

> What's the reason for having the mode "pt"?

This is an artifact for/from the simulation, basically to distinguish car and non-car modes. However I'm not quite sure about that @sebhoerl?

**Comment by sebhoerl** [comment]
The `pt` mode is basically only a "hint" in the network file, usually it is not really used. I think mainly it is useful for visualization, for instance to put a different color on links that are not useable by "car". And note that the "bus" or "rail" modes that pt2matsim adds are also mainly used inside of pt2matsim to perform the matching of lines to the network. Once the routes through the network (i.e. the sequences of links) for a transit line are established (as an output of pt2matsim), MATSim does not really perform any routing with them anymore and hence it does not really care about what allowedModes are assigned to a link.

On the contrary, "car" legs are constantly re-routed in MATSim, so it is important for the router to know which links are accessible by car. Hope that helps?

**Comment by CianGraham** [comment]
That's much clear. Thanks, guys
