### ISSUE TITLE
(Stop) IDs with spaces in GTFS schedules

### ISSUE THREAD

**Issue by sebhoerl** [matsim-org/pt2matsim#122]
The [GTFS schedule from SNCF for their TER trains](https://ressources.data.sncf.com/explore/dataset/sncf-ter-gtfs/) contains spaces in the stop ids. According to the GTFS reference, this seems to be valid, as it only needs to be a "sequence of UTF-8 characters". Also, `pt2matsim` handles those stops well. However, they become a problem later in MATSim, because the `NetworkRoute`s of the lines are encoded as `[link 1] [link 2] [link 3]`, etc., basically link IDs separated by spaces. If `pt2matsim` now creates artificial links based on stop IDs with spaces inside the ID, the sequence of links gets messed up.

There are probably two points of access to this problem:
1) Directly treat IDs with spaces while reading the schedule (potentially leading to rare cases of "creating" a new ID that already exists)
2) Treat the IDs when creating the artificial links. I didn't go deeper in the code yet to see if there is a single point where this can happen, or if there are places where we convert between Link <-> Stop IDs later on. Probably @polettif knows more :)

**Comment by polettif** [comment]
> 1. Directly treat IDs with spaces while reading the schedule (potentially leading to rare cases of "creating" a new ID that already exists)

Which schedule, the GTFS feed or the unmapped MATSim schedule? I wouldn't change IDs upon reading since this might be unexpected. Handling them in GTFSConverter sounds better. There, quite a "low level" treatment of gtfs IDs is probably necessary since IDs are used throughout the feed.

> Treat the IDs when creating the artificial links. I didn't go deeper in the code yet to see if there is a single point where this can happen, or if there are places where we convert between Link <-> Stop IDs later on. 

This approach might be easier, just change [createArtificialLinkId](https://github.com/matsim-org/pt2matsim/blob/80c688e1b328d981d99af3b206e717f235c355e5/src/main/java/org/matsim/pt2matsim/tools/PTMapperTools.java#L238). I _think_ once an artificial link has been created its ID isn't used to infer stop IDs or converted further, basically it could be any hash-like string (unlike child stopFacility IDs with a `.link:` which are parsed in reverse). And even if someone depends on this in a current workflow, simply replacing spaces shouldn't change or break anything for them.
