### ISSUE TITLE
Projected coordinates are in wrong axis order

### ISSUE THREAD

**Issue by shanataru** [matsim-org/pt2matsim#156]
Hello,

I have an issue with transforming spherical coordinates of Prague from an OSM file to the Krovak projection. 
Czechia officially uses [EPSG:5514](https://epsg.io/5514), however due to the geotools error ("No transform for classification "Krovak (North Orientated)"), I am using [EPSG:5513](https://epsg.io/5513) instead.

The final multimodal network has correctly calculated coordinates, the only problem is that the x and y are flipped. I understand that the problem is most likely in _geotools_ library and how it defines the axis order for EPSG:5513. However, is there a way I could resolve this problem through MATSim/pt2matsim only? 

Thank you in advance.

**Comment by JWJoubert** [comment]
Hi @shanataru, yes, this is a real pain in the butt. We have a similar issue in South Africa. Not only is our `x` and `y` switched, but we are also _south oriented_! So, the more south the location, the more _positive_ the coordinate value  ;)

The way in which I do it when using `pt2matsim` is to use some (any!!) projected coordinate system. You can use UTM, `EPSG:5513`, whatever. Then, once the conversions are done, I write the network to file. I then simply read the MATSim network in, using the methods
```
new MatsimNetworkReader("EPSG:5513", yourActualCrs, network).readFile(networkFile);
new NetworkWriter(network).write(networkFile);
```
Now, granted, this works for me because in the MATSim core there are specific coordinate reference systems defined in the classes `org.matsim.core.utils.geometry.transformations.TransformationFactory` and `org.matsim.core.utils.geometry.geotools.MGC` that caters for our South African  cases. So, my `yourActualCrs` might be something like `TransformationFactory.SA_Lo29`.

Unfortunately, `pt2matsim` _only_ works with valid EPSG codes. I know it is on @mrieser 's radar to (one day) accommodate these "flipped" coordinate references systems into Via as well.

Good luck!

**Comment by JWJoubert** [comment]
Just to make it clear, @shanatar : the problem is _not_ with `pt2matsim` for doing the conversion incorrectly, but rather that the (most) visualisation tools cannot honour the flipped axes.

**Comment by shanataru** [comment]
Dear @JWJoubert, thank you for your input.

It is unfortunate for me that there is no specific CRS in those classes for Czechia case. I am currently searching for a manual solution, which could later work with mapping the public transit from GTFS as well.

As you said, `pt2matsim` only works with valid EPSG codes, thus I cannot just specify a WKT string for Krovak to have the coordinates flipped correctly using the class `org.geotools.referencing.CRS`. 

Another idea was switching the longitude and latitude in the original OSM file, but I am not sure it is the correct way to deal with this issue.

**Comment by JWJoubert** [comment]
> The visualisation tool will have to deal with it afterwards 😄

Unfortunately, it most likely _won't_ be able to deal with it, @shanataru. If you want to send the WKT, I can create a pull request in the MATSim core. I cannot see that one/two lines of code in the core will make a huge difference. It is not affecting code maintenance as it is simply a static `String`. Once approved, you should just have to update your MATSim dependency and then you should be able to apply my "hack".

**Comment by shanataru** [comment]
Hi @JWJoubert,
if it is possible to use your hack, that would be ideal!

I would prefer EPSG:5514 instead, because it is officially supported in Czechia:
```
PROJCS["Czech GIS S-JTSK (Greenwich) / Krovak",
   GEOGCS["Czech S-JTSK (Greenwich)",
       DATUM["Czech S-JTSK",
           SPHEROID["Bessel 1841",6377397.155,299.1528128,
               AUTHORITY["EPSG","7004"]],
           TOWGS84[570.8,85.7,462.8,4.998,1.587,5.261,3.56]],
       PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], 
       UNIT["degree",0.0174532925199433]],
   PROJECTION["Krovak",
       AUTHORITY["EPSG","9819"]],
   PARAMETER["latitude_of_center",49.5],
   PARAMETER["longitude_of_center",24.83333333333333],
   PARAMETER["azimuth",0],
   PARAMETER["pseudo_standard_parallel_1",0],
   PARAMETER["scale_factor",0.9999],
   PARAMETER["false_easting",0],
   PARAMETER["false_northing",0],
   UNIT["Meter",1],
   AXIS["X",EAST],
   AXIS["Y",NORTH],
   AUTHORITY["EPSG","5514"]]
```

And in proj format:
```
+proj=krovak +lat_0=49.5 +lon_0=24.83333333333333 +alpha=30.28813972222222 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +pm=greenwich +units=m +no_defs +towgs84=570.8,85.7,462.8,4.998,1.587,5.261,3.56
```


Thank you!

**Comment by JWJoubert** [comment]
No problem, @shanataru. I created the [pull request](https://github.com/matsim-org/matsim-libs/pull/1706) and will let you know if it passes/gets approved.

**Comment by shanataru** [comment]
Thank you, @JWJoubert, this is great news!
