### ISSUE TITLE
Infinite loop while mapping when loop-link exists in the network

### ISSUE THREAD

**Issue by sebhoerl** [matsim-org/pt2matsim#66]
I just tried to create a new network and schedule from the current Geofabrik OSM Snapshot of Switzerland + SBB GTFS / HAFAS. Unfortunately, the mapping doesn't work. It goes in a infinite loop in `NetworkTools::reduceSequencedLinks`. 

The reason is that in the network construction a loop-link is introduced (ID `689236`). If this link is fed into this function the first do-while loop (line 526) always finds the same link as the preceding link of the current one and so it never exits. As I'm not 100% sure what exactly this function is doing and what implications my changes may have, it's maybe good if @polettif could have a look :)

Example input to `PublicTransitMapper` can be found here:
https://polybox.ethz.ch/index.php/s/dYBNKGGoQYnjIfV

**Comment by sebhoerl** [comment]
I added a PR, not sure if it has any other side effects. But unit tests pass and the mapping also is getting past that point (didn't finish the whole process yet, though).

**Comment by sebhoerl** [comment]
I just tested with the latest Switzerland Geofabrik SNAPSHOT + latest SBB HAFAS / GTFS, and now it runs through smoothly (with that PR). 

Not sure, why this error did not happen before? Can it be that something has changed in the OSM converter, which no produces loop links and did not before?

**Comment by polettif** [comment]
Yes #66 fixes the problem, thanks. The actual bug is in the getSingleFile*Link methods when they return loop links or something like that. I wasn't able to pinpoint the bug or cover it with a test quickly.

> Not sure, why this error did not happen before? Can it be that something has changed in the OSM converter, which no produces loop links and did not before?

Good question... I did change the osm converter in march, so maybe there was a bug introduced there but the changes mostly affected the config an not the actual conversion. This does fix the problem though.

`reduceSequencedLinks` is a preprocessing function for the mapping. The idea is: If there are multiple links in single file (i.e. only one road consisting of multiple links), only the link that's closest to the stop coordinates is considered as link candidate. This reduces the number of link candidates although the speed increase is debatable. Now to think of it, this preprocessing is not really necessary anymore. Previously, for directly succeding link candidates there's no explicit "best" link candidate. Now the link candidate travel cost considers the distance to the stop coordinate, so pre-selecting candidates is not really necessary. In the spirit of "never change a (now fixed) system", I'd say we leave it in.
