### ISSUE TITLE
Empty line in Stops.txt

### ISSUE THREAD

**Issue by MAlbertini95** [matsim-org/pt2matsim#90]
Hi, I get an error while trying to generate the schedule fro GTFS. It says empty line in Stops.txt file, but I can't see the problem in the file. Do i have to reduce the information in the file only to the ones needed?
Thank you

**Comment by polettif** [comment]
That's hard to tell without the actual files. In general, removing the empty line should fix the issue. Please post a link to the feed if it doesn't.

**Comment by MAlbertini95** [comment]
I tried to simplify the file but it doesn't work and I can't see any clear error in the original file. Here I post the link to the GTFS source used. Hope you can give me some advice to overcome this problem.
[google_transit_urbano_tte.zip](https://github.com/matsim-org/pt2matsim/files/3315945/google_transit_urbano_tte.zip)

**Comment by polettif** [comment]
The problem is not an empty line but mixing `"` and `'` on line 855 of stops.txt:
```
2790,22565c,Spini "Casa Circondariale',,46.127009,11.096719,10110,1
```
I updated the error messages to include the line number. 

Just a heads up, the feed seems to have more problems, for example trip_ids used in stop_times don't exist in trips.txt. You can use feed validators (e.g. [GTFS.html](https://gtfs.pleasantprogrammer.com/) or [transitscreen](https://gtfsfeedvalidator.transitscreen.com/), there are others out there) to find errors. Unfortunately, you need to fix them either by hand or using a script before running pt2matsim.
